### PR TITLE
Fix RDMD callout titles.

### LINKED ISSUE #652: Using inline code syntax in callout titles only renders code
Writing something like this:

> 🚧 Make sure you're sending `postData` correctly!
> 
> According to the [HAR specification](http://www.softwareishard.com/blog/har-12-spec/#postData), a [`params` array](http://www.softwareishard.com/blog/har-12-spec/#params) should only be sent "in case of URL encoded parameters". So for JSON MIME types, [stringify the JSON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) and send it as `postData.text`.
>
> If you have any questions, [please contact us](mailto:support@readme.io?subject=API%20Metrics%20Integrations)!

yields this (note the title):

image

### PR DESCRIPTION
**Pull request by rafegoldberg**
## 🧰 What's being changed?

Resolves #652.

## 🧪 Testing

Check it out here.

## 🗳 Checklist

* 🐛 I'm fixing a bug

### CODE REVIEW

File: packages/markdown/processor/parse/magic-block-parser.js [hunk 1]
```diff
@@ -189,7 +189,8 @@ function tokenize(eat, value) {
         .split(/(?:www)?\./)
         .filter(i => i)
         .join('')}`;
-      const data = { url, html, title, provider: json.provider };
+      const data = { url, html, title, provider: json.provider, iframe: json.iframe };
+      console.log({ json, extract: { title, url, html, data } });
```
Comment (erunion) [inline packages/markdown/processor/parse/magic-block-parser.js:193]:
```suggestion
```

**Comment by rafegoldberg** [comment]
totally fucked on a technicality; guess I'll be eating my 🎩...

```
@readme/markdown: Jest: "global" coverage threshold for branches (88%) not met: 87.83%
```

**Comment by rafegoldberg** [comment]
HA
